// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services.proto

package com.chaos.remoting.grpc;

public final class Services {
  private Services() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016services.proto\022\027com.chaos.remoting.grp" +
      "c\032\016messages.proto2\373\001\n\017RemotingService\022p\n" +
      "\007execute\0220.com.chaos.remoting.grpc.Remot" +
      "eInvocationRequest\0321.com.chaos.remoting." +
      "grpc.RemoteInvocationResponse\"\000\022v\n\rgetRe" +
      "moteInfo\0220.com.chaos.remoting.grpc.Remot" +
      "eInvocationRequest\0321.com.chaos.remoting." +
      "grpc.RemoteInvocationResponse\"\000B\002P\000b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.chaos.remoting.grpc.Messages.getDescriptor(),
        }, assigner);
    com.chaos.remoting.grpc.Messages.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
